version: '3'

services:
  n8n:
    container_name: n8n
    image: n8nio/n8n
    restart: always
    ports:
      - 5678:5678
    environment:
      - NODE_ENV=production
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_PROTOCOL=https
      - TZ=Asia/Bangkok
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - n8n_network
  ngrok:
    image: ngrok/ngrok
    restart: unless-stopped
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTH}
    command: http n8n:5678
    networks:
      - n8n_network
    volumes:
      - ngrok_config:/home/ngrok/.config/ngrok

volumes:
  n8n_data:
    external: true
  ngrok_config:

networks:
  n8n_network:
    driver: bridge

